name: CI/CD Pipeline for AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir -p python
        pip install -r requirements.txt -t ./python

    - name: Package dependencies for Layer
      run: |
        cd python
        zip -r dependencies_payload.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Publish a new version of Lambda Layer
      id: publish-layer-version
      run: |
        LAYER_VERSION=$(aws lambda publish-layer-version --layer-name justalayer --zip-file fileb://./python/dependencies_payload.zip --compatible-runtimes python3.11 | jq '.LayerVersionArn' -r)
        echo "LAYER_VERSION_ARN=$LAYER_VERSION" >> $GITHUB_ENV

    # Assuming you have handler functions named 'lambda_function.lambda_handler' for both 
    - name: Create Lambda function - Retrieve
      run: |
        aws lambda create-function --function-name retrieve_data_from_rds --runtime python3.11 --role arn:aws:iam::859158209175:role/lambda-role-for-acmecorp --handler lambda_function.lambda_handler

    - name: Create Lambda function - Read
      run: |
        aws lambda create-function --function-name read-from-s3 --runtime python3.11 --role arn:aws:iam::859158209175:role/lambda-role-for-acmecorp --handler lambda_function.lambda_handler

    - name: Update Lambda function code with new Layer - Retrieve
      run: |
        aws lambda update-function-configuration --function-name retrieve_data_from_rds --layers $LAYER_VERSION_ARN

    - name: Update Lambda function code with new Layer - Read
      run: |
        aws lambda update-function-configuration --function-name read-from-s3 --layers $LAYER_VERSION_ARN
